### ISSUE TITLE
Request: Add Ability to Reset SerializerBuilder

### ISSUE THREAD

**Issue by paulsavides** [SimonCropp/ObjectApproval#45]
#### The Problem

For certain test cases, we wish to use certain serializer settings (particularly using `IgnoreMember(Type declaringType, string name)` ). But it would be nice if these did not persist to other test cases.

We have implemented scrubbers in situations where that is appropriate (e.g., range and/or formatting validation). But for certain cases where we are only verifying something very targeted, being able to use custom serializer settings per test run would be helpful.

#### Potential Solution(s)

Regardless, we would need to add a `public static void Reset()` method onto `SerializerBuilder`.

The simplest solution would be to have the reset function just reset all private fields and properties on the static class to the default values.

Or, could move the storage of settings overrides to some private singleton class and the reset could be done by simply performing `settingsStorage = new SerializerBuilderSettingsStorage()` and have the constructor do the appropriate initialization.

Either way, if you would be willing to accept a change like this I could make a pull request with one of these solutions.

Thank you for your time.

**Comment by SimonCropp** [comment]
there is an overload of `VerifyWithJson` that accepts both a `JsonSerializerSettings` and a scrubber. would that be sufficient for your requirements?

**Comment by SimonCropp** [comment]
@paulsavides @jvonruden thoughts one my comment?

**Comment by paulsavides** [comment]
@SimonCropp, apologies for the delay.

If we were to use the override that accepted the `JsonSerializerSettings` we would need to rewrite most of the logic that the `SerializerBuilder` class is doing. As in, we want to use what that class provides more dynamically; the override doesn't really get us further to that goal.

**Comment by SimonCropp** [comment]
ok can you submit a PR with what you have in mind

**Comment by SimonCropp** [comment]
@paulsavides does this work for you https://github.com/SimonCropp/ObjectApproval#scoped-settings  ?
