### ISSUE TITLE
Obsolete VerifyWithJson. Use Verify instead

### ISSUE THREAD

**Issue by SimonCropp** [SimonCropp/ObjectApproval#77]
use `ObjectApproval.Verify`

The original intent was to have multiple serialization options for visualizing data. Now it seems Json is sufficient.

**Comment by michael-freidgeim-webjet** [comment]
It will be good to have "Breaking Changes" document that will list changes like this.

**Comment by SimonCropp** [comment]
@michael-freidgeim-webjet  sorry, i currently maintain a significant number of projects https://www.nuget.org/profiles/simoncropp. I am unlikely to have the time to maintain a "Breaking Changes" document moving forward
